### PR TITLE
Fix #13349: Replace string concatenation with operator<< in logs

### LINKED ISSUE #13349: Replace string + concatenation in log statements with `operator<<`
**This is an [Easy Hack](https://collaboraonline.github.io/post/easyhacks/).**
Potential mentors: @Darshan-upadhyay1110 @lpranam 

### Detailed description and rationale
Our logging style prefers using stream insertion (<<) instead of string + concatenation inside logging macros. Some places still use + to build log messages, which creates unnecessary temporary strings.

#### Example (current code to fix)

```cpp
LOG_INF("User " + user + " connected");
LOG_ERR("Failed: " + reason + " at " + location);
```

####  Desired style

```cpp
LOG_INF("User " << user << " connected");
LOG_ERR("Failed: " << reason << " at " << location);
```

####  Guidelines

* Do **not** rewrite regular string building in non-logging code.
* Ensure the log output text stays identical.
* Build after changes to confirm no format issues.

####  How to find candidate lines

```sh
git grep -E 'LOG_.*".*\+' -- '*.cpp' '*.hpp'
```

### PR DESCRIPTION
**Pull request by andrachiritoiu**
Change-Id: I7ac75450c7507f44bd37cfaeb4be895a397809f1

* Resolves: #13349
* Target version: master 

### Summary
Replaced string concatenation (`+`) with the stream operator (`<<`) in log statements to improve performance and match the project coding standards. This fixes the reported easy hack.

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by andrachiritoiu** [comment]
It seems the mobile cypress test timed out (infrastructure issue). Could you please re-run the checks?

**Comment by eszkadev** [comment]
> It seems the mobile cypress test timed out (infrastructure issue). Could you please re-run the checks?

done :) but unfortunately there is a conflict in some file, please rebase

**Comment by andrachiritoiu** [comment]
I have rebased the branch and resolved the conflicts as requested. Thanks!

**Comment by Darshan-upadhyay1110** [comment]
hi @Ashod & @eszkadev can you please review this ? the CI seems to be okay now...

File: wsd/COOLWSD.cpp [hunk 1]
```diff
@@ -3598,7 +3598,7 @@ void COOLWSD::innerMain()
     }
     if (locale)
     {
-        LOG_INF("Locale is set to " + std::string(locale));
+        LOG_INF("Locale is set to " << std::string(locale));
```
Comment (Ashod) [inline wsd/COOLWSD.cpp:3601]: `std::string()` is no longer needed.
