### PR TITLE
remoteConfig: reload lokit environment variables

### LINKED ISSUE #13727: Inserting image doesn't work : lok_allow not taking alias_group into account.
### Describe the Bug

When I edit a document opened from a Nextcloud and I want to insert an image from my nextcloud into the document, I can browse my files, but when I click "insert file", nothing happen, and collabora logs this: 

```
dec. 03 11:07:47 hostname coolwsd[1931654]: kit-1931654-1931654 2025-12-03 11:07:47.068565 +0100 [ kitbroker_2137 ] ERR  ToMaster-4a0e2: CALLBACK_ERROR: { "code": 24581, "kind": "network", "cmd": "insert"}| kit/ChildSession.cpp:3742
dec. 03 11:07:47 hostname coolwsd[1931654]: kit-1931654-1931654 2025-12-03 11:07:47.068686 +0100 [ kitbroker_2137 ] ERR  ToMaster-4a0e2: error: cmd=insert kind=network code=24581| common/Session.hpp:181
```

We found a way to reproduce, stated below:

### Steps to Reproduce

1. Install collabora
2. Setup the configuration to have a remote_config url
3. This remote_config URL spit out a JSON file containing a storage > wopi > alias_groups > groups > host > "https://mynextcloud.com" 
4. open an ODT document from mynexcloud.com using this collabora
5. The document opens properly
6. click Insert > Illustration > Image > Image... and select an image from your nextcloud
7. click "insert this file" => nothing happen

To make it work we MUST add mynextcloud.com in the lok_allow key in the coolwsd.xml configuration **statically**

### Expected Behavior

I expect lok_allow to be a dynamic configurable list too. 

We tried to setup the remote_config with a lok_allow key too as follow: 

```
{ "kind":"configuration", "net": { "lok_allow": { "hosts" : ["mynextcloud.com"]  }   }  }
```

but it didn't work.

### Actual Behavior

lok_allow is a static configuration list, it's seems to be read at boottime and can't be modified later.

 - **Collabora version:** collabora online lite version 25.04.7-3
 - **OS and version:** server running Debian 12
 - **Browser and version:** Chrome 142

### PR DESCRIPTION
**Pull request by meven**
When the remote config changes.
This will allow subsequent lokit to use the updated hosts and alias_groups.

Share the implementation in COOLWSD through static access.

Reuse RegexUtil::isRegexValid in COOLWSD.

Change-Id: I24011e514799fd34bf6d5a6514748fed8046726f

* Resolves: # 
* Target version: master 

### Summary

Fixes #13727

### Checklist

- [x] I have run `make prettier-write` and formatted the code.
- [x] All commits have Change-Id
- [x] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

File: common/RegexUtil.cpp [hunk 1]
```diff
@@ -119,14 +120,12 @@ bool isRegexValid(const std::string& regex)
...
-        // Not performance critical to warrant caching.
-        Poco::RegularExpression re(regex, Poco::RegularExpression::RE_CASELESS);
+        std::regex re(regex);
         return true;
     }
-    catch (const std::exception& exc)
-    {
-        return false;
-    }
+    catch (const std::regex_error& exc){}
```
Comment (Ashod) [inline common/RegexUtil.cpp]: `exc` is unused and can be removed.

File: common/RegexUtil.cpp [hunk 2]
```diff
@@ -119,14 +120,12 @@ bool isRegexValid(const std::string& regex)
 {
     try
     {
-        // Not performance critical to warrant caching.
-        Poco::RegularExpression re(regex, Poco::RegularExpression::RE_CASELESS);
+        std::regex re(regex);
```
Comment (Ashod) [inline common/RegexUtil.cpp]: Are we certain this is identical to `Poco::RegularExpression` with `RE_CASELESS` ?

Comment (meven) [reply common/RegexUtil.cpp]: [std::regex_constants::icase](https://en.cppreference.com/w/cpp/regex/syntax_option_type.html)

We'd want:
```suggestion
        std::regex re(regex, std::regex_constants::icase);
```

Comment (meven) [reply common/RegexUtil.cpp]: Poco::RegularExpression is PCRE and std::regex is POSIX syntax (by default ECMASCRIPT).

But the current aliasHost validation made PCRE regex, not POSIX-compatible, could never be passed as env variable or be invalid as this stage used `std::regex` instead.

This keeps this consistent but generalizes the `std::regex` validation using it in `HostUtil::parseAliases` as well.

We could go the opposite way and generalize `Poco::RegularExpression`. It just seems better to go to `std` solution rather than `Poco`.

We can also pick other std::regex dialects that is supports like ECMASCRIPT to be consistent with browsers.

Comment (meven) [reply common/RegexUtil.cpp]: Also the backend can't support Poco::RegularExpression. So any regex passed to the backend must be std::regex.

Those regex are used in:
libreoffice/core/tools/source/inet/hostfilter.cxx

Comment (Ashod) [reply common/RegexUtil.cpp]: Thanks. It's good to standardize on `std::regex`. My concern is that this breaks existing configs. If we are sure we won't break anything, then fine.

File: wsd/COOLWSD.cpp [hunk 3]
```diff
@@ -2227,6 +2182,45 @@ void COOLWSD::innerInitialize(Poco::Util::Application& self)
...
+            if (RegexUtil::isRegexValid(lokAllowedHosts[i]))
+                allowedRegex += (i != 0 ? "|" : "") + lokAllowedHosts[i];
+            else
+                LOG_ERR("Invalid regular expression for allowed host: \"" << lokAllowedHosts[i] << "\"");
+        }
+
+        setenv("LOK_HOST_ALLOWLIST", allowedRegex.c_str(), true);
+
+#if !MOBILEAPP
+        if (!ConfigUtil::getConfigValue<bool>(conf, "ssl.ssl_verification", true)) {
```
Comment (Ashod) [inline wsd/COOLWSD.cpp]: Could be converted to C++ formatting.

File: common/RegexUtil.cpp (hunk 2 above)
Comment (meven) [reply common/RegexUtil.cpp]: > Thanks. It's good to standardize on std::regex. My concern is that this breaks existing configs. If we are sure we won't break anything, then fine.

If we break anything, those configs would not be valid today: LOK uses std::regex.
