### PR TITLE
Show drag preview of unselected shapes

### LINKED ISSUE #7821: Draw: Select+Drag make drag without feedback
### Describe the Bug
When you select + drag an object, the drag (move) happen without feedback.

### Steps to Reproduce
1. Open a draw document with some content
2. Click and drag on a shape to move it

### Expected Behavior
The shape follow the mouse cursor and when you release it get moved there.

### Actual Behavior
When you release the mouse it will have moved as expected, but otherwise you don't have feedback.

### Screenshots

[Screencast from 2023-12-11 15-39-13.webm](https://github.com/CollaboraOnline/online/assets/114441/29f8302a-3df2-445c-94f1-bd7d79072469)

The video show the select + drag vs just drag.

### Desktop

COOLWSD version: 23.05.6.1 (git hash: 65a85cda)
LOKit version: Collabora Office 23.05.6.2 (git hash: a6b78ba)
Served by: Fedora Linux 38 (Container Image)
Server ID: 55888ee5

(Please complete the following information)
 - **Collabora version:** [e.g. 23.05.5.3]
 - **OS and version:** [e.g. Windows 11]
 - **Browser and version:** [e.g. Chrome 114.0]

### PR DESCRIPTION
**Pull request by GulsahKose**
When dragging starts on an unselected shape, MouseControl owns the
drag because ShapeHandlesSection does not exist yet.  Core selects
the shape in response to our deferred buttondown and sends back a
graphicselection message which creates ShapeHandlesSection and
fetches an SVG.  Once the SVG arrives we can show it as a
semi-transparent drag preview, matching the behavior that
ShapeHandlesSection.onMouseMove provides for already-selected shapes.

Change-Id: If3c6fef682d9b4e2d3778d3acbc884af80b2e2c3

* Resolves: #7821 
* Target version: main

### TODO

- [ ] ...

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by GulsahKose** [comment]
Hi @eszkadev Most probably this kind of fails are expected for this patch, right?

File: browser/src/canvas/CanvasSectionContainer.ts [hunk 1]
```diff
@@ -1204,7 +1204,9 @@ class CanvasSectionContainer {
 						this.sectionUnderMouse = section.name;
 						this.propagateOnMouseEnter(section, this.convertPositionToSectionLocale(section, this.mousePosition), e);
 					}
-					this.propagateOnMouseMove(section, this.convertPositionToSectionLocale(section, this.mousePosition), this.dragDistance, e);
+					// Prevent to dragging something without select.
+					if(this.sectionUnderMouse !== "selection-rectangle" && this.sectionUnderMouse !== "overlay")
```
Comment (eszkadev) [inline browser/src/canvas/CanvasSectionContainer.ts]: - `if(` -> `if (`
- doesn't that block all mouse move events on a canvas? it is used to change cursor in some places etc.
- isn't that easy to block it in the core? like: `when we have mouse move event on shape which is not selected -> just select it and finish in LOK case` ?

**Comment by GulsahKose** [comment]
Hi @eszkadev , That is completely new patch that shows drag preview of  unselecetd shapes.

**Review by eszkadev — APPROVED** [review]
works good for most shapes also with different zoom-level
