### PR TITLE
NB: Adds Character spacing to home tab

### LINKED ISSUE #2149: Notebookbar Character Spacing
**Describe the bug**
Character Spacing isn't availbale at cool.

2021-04-26 11_08_36-Untitled 1 - LibreOfficeDev Writer

### PR DESCRIPTION
**Pull request by pedropintosilva**
- Fixes #2149

Signed-off-by: Pedro Pinto Silva <pedro.silva@collabora.com>
Change-Id: Ib10ebe68fa46d170787d11b06e07a5641f7e7990

### CODE REVIEW

**Comment by pedropintosilva** [comment]
this is a WIP

File: loleaflet/src/control/Control.NotebookbarBuilder.js [hunk 1]
```diff
@@ -625,6 +626,38 @@ L.Control.NotebookbarBuilder = L.Control.JSDialogBuilder.extend({
...
+			};
+
+			$(control.container).w2menu({
+				items: [
+					{id: 'spacepara1', img: 'spacepara1', text: _UNO('.uno:SpacePara1'), uno: 'SpacePara1', checked: isChecked('.uno:SpacePara1')},
+					{id: 'spacepara15', img: 'spacepara15', text: _UNO('.uno:SpacePara15'), uno: 'SpacePara15', checked: isChecked('.uno:SpacePara15')},
+					{id: 'spacepara2', img: 'spacepara2', text: _UNO('.uno:SpacePara2'), uno: 'SpacePara2', checked: isChecked('.uno:SpacePara2')},
+					{type: 'break'},
+					{id: 'paraspaceincrease', img: 'paraspaceincrease', text: _UNO('.uno:ParaspaceIncrease'), uno: 'ParaspaceIncrease'},
+					{id: 'paraspacedecrease', img: 'paraspacedecrease', text: _UNO('.uno:ParaspaceDecrease'), uno: 'ParaspaceDecrease'}
```
Comment (pedropintosilva) [inline loleaflet/src/control/Control.NotebookbarBuilder.js:651]: this should be replaced with the correspondent UNO commands for increasing and decreasing character (which I don't seem to find)

Comment (pedropintosilva) [reply loleaflet/src/control/Control.NotebookbarBuilder.js:651]: couldn't find them in https://wiki.documentfoundation.org/Development/DispatchCommands nor searching in core. @eszkadev pointed that `.uno:Spacing?Spacing:short=60` should work. 

It didn't, probably because I should do something else?

**Comment by Andreas-Kainz** [comment]
Cool with this patch noteboolbar is done for the moment. Cool @pedropintosilva

**Comment by Andreas-Kainz** [comment]
very cool that you work on it.

**Comment by pedropintosilva** [comment]
_rebasing, solving conflicts, update directory according to master_
