### PR TITLE
calc: Implement hiding the grid lines

### LINKED ISSUE #8066: (calc): no possibility to hide the gridlines
There is no option to hide the grid lines. The instructions are incorrect: there is no "Extras" "Options" menu item

### PR DESCRIPTION
**Pull request by hfiguiere**
Fixes #8066

Requires https://gerrit.libreoffice.org/c/core/+/166647

Change-Id: I2196e1a8e654a8afd20519b18f00cefafa048f2c

* Resolves: #8066
* Target version: master 

### Summary

We now show / hide the grid in the spreadsheet.
Requires LOKit patch.

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

File: browser/src/layer/tile/CalcTileLayer.js [hunk 1]
```diff
@@ -839,6 +840,14 @@ L.CalcTileLayer = L.CanvasTileLayer.extend({
 			*/
 			this.insertMode = e.state.trim() === '' ? false: true;
 		}
+		else if (e.commandName === '.uno:ToggleSheetGrid') {
+			let newState = e.state.trim() === 'true';
+			if (this._sheetGrid != newState) {
+				this._sheetGrid = newState;
+				// Trigger redraw.
+				this._map.fire('sheetgeometrychanged');
```
Comment (hfiguiere) [inline browser/src/layer/tile/CalcTileLayer.js:848]: I am unsure if that's the best event to fire to trigger a complete redraw. I'm afraid it might stop working. I didn't find one to for redraw otherwise.

**Comment by hfiguiere** [comment]
image

image

**Comment by hfiguiere** [comment]
image


image

**Comment by hfiguiere** [comment]
Rebased and changed how the redraw is triggered.

File: browser/src/layer/tile/CalcTileLayer.js (hunk 1 above)
Comment (hfiguiere) [reply browser/src/layer/tile/CalcTileLayer.js]: I call `this._painter._sectionContainer.requestReDraw()` directly.

**Review by caolanm — APPROVED** [review]
This looks reasonable to me

**Comment by hfiguiere** [comment]
Failure similar to https://github.com/CollaboraOnline/online/pull/8902#issuecomment-2079462730

**Comment by caolanm** [comment]
I think best to rebase this to get the "Cypress: Fix mobile/impress/apply_font_text_spec.js" fix in

**Comment by caolanm** [comment]
green now, seems sensible
